"""Regenerate docs/reference.md from the cadence package public API.

Local equivalent of a doc-generation skill (for example GStack /document-release or
/document-generate). Diataxis quadrant: reference (information-oriented). The output is
deterministic, so the doc-vs-code consistency gate can diff it against the live API.

Run: uv run python -m tools.make_docs
"""

from __future__ import annotations

import importlib
import inspect
from pathlib import Path

_MODULES = ("catalog", "users", "recommender", "rationale", "provenance", "cli")


def public_api():
    """Return [(module, name, kind, signature, one_line_doc)] for every public symbol."""
    items = []
    for mod in _MODULES:
        m = importlib.import_module(f"cadence.{mod}")
        for name, obj in inspect.getmembers(m):
            if name.startswith("_"):
                continue
            defined_here = getattr(obj, "__module__", None) == m.__name__
            if inspect.isfunction(obj) and defined_here:
                doc = (inspect.getdoc(obj) or "").split("\n")[0]
                items.append((f"cadence.{mod}", name, "function", str(inspect.signature(obj)), doc))
            elif inspect.isclass(obj) and defined_here:
                doc = (inspect.getdoc(obj) or "").split("\n")[0]
                items.append((f"cadence.{mod}", name, "class", "", doc))
    return items


def render(items) -> str:
    lines = [
        "# Cadence API reference",
        "",
        "Generated by tools/make_docs.py from the cadence package. Do not edit by hand.",
        "Diataxis quadrant: reference (information-oriented).",
    ]
    current = None
    for module, name, kind, sig, doc in items:
        if module != current:
            lines += ["", f"## {module}", ""]
            current = module
        if kind == "function":
            lines.append(f"- `{name}{sig}` (function) - {doc}")
        else:
            lines.append(f"- `{name}` (class) - {doc}")
    return "\n".join(lines) + "\n"


def main(write: bool = True) -> str:
    items = public_api()
    text = render(items)
    if write:
        Path("docs/reference.md").write_text(text)
        print(f"wrote docs/reference.md ({len(items)} public symbols)")
    return text


if __name__ == "__main__":
    main()
